#define _CRT_SECURE_NO_DEPRECATE
#include <stdio.h>
#include <stdlib.h>

int main() {
	char p1[50], p2[50], p3[50], p4[50], p5[50], p6[50], p7[50], p8[50], p9[50], p10[50], p11[50], p12[50], p13[50], p14[50], p15[50], p16[50], p17[50], p18[50], p19[50], p20[50];
	
	printf("Introduce un nombre: ");
	fgets(p1, 50, stdin);
	//scanf("%s", &p1);
	printf("Valido \n");
	system("pause");
	system("cls");
	printf("Introduce un nombre: ");
	fgets(p2, 50, stdin);
	//scanf("%s", &p2);
	printf("Valido \n");
	system("pause");
	system("cls");
	printf("Introduce un nombre: ");
	fgets(p3, 50, stdin);
	//scanf("%s", &p3);
	printf("Valido \n");
	system("pause");
	system("cls");
	printf("Introduce un nombre: ");
	fgets(p4, 50, stdin);
	//scanf("%s", &p4);
	printf("Valido \n");
	system("pause");
	system("cls");
	printf("Introduce un nombre: ");
	fgets(p5, 50, stdin);
	//scanf("%s", &p5);
	printf("Valido \n");
	system("pause");
	system("cls");
	printf("Introduce un nombre: ");
	fgets(p6, 50, stdin);
	//scanf("%s", &p1);
	printf("Valido \n");
	system("pause");
	system("cls");
	printf("Introduce un nombre: ");
	fgets(p7, 50, stdin);
	//scanf("%s", &p1);
	printf("Valido \n");
	system("pause");
	system("cls");
	printf("Introduce un nombre: ");
	fgets(p8, 50, stdin);
	//scanf("%s", &p1);
	printf("Valido \n");
	system("pause");
	system("cls");
	printf("Introduce un nombre: ");
	fgets(p9, 50, stdin);
	//scanf("%s", &p1);
	printf("Valido \n");
	system("pause");
	system("cls");
	printf("Introduce un nombre: ");
	fgets(p10, 50, stdin);
	//scanf("%s", &p1);
	printf("Valido \n");
	system("pause");
	system("cls");
	printf("Introduce un nombre: ");
	fgets(p11, 50, stdin);
	//scanf("%s", &p1);
	printf("Valido \n");
	system("pause");
	system("cls");
	printf("Introduce un nombre: ");
	fgets(p12, 50, stdin);
	//scanf("%s", &p1);
	printf("Valido \n");
	system("pause");
	system("cls");
	printf("Introduce un nombre: ");
	fgets(p13, 50, stdin);
	//scanf("%s", &p1);
	printf("Valido \n");
	system("pause");
	system("cls");
	printf("Introduce un nombre: ");
	fgets(p14, 50, stdin);
	//scanf("%s", &p1);
	printf("Valido \n");
	system("pause");
	system("cls");
	printf("Introduce un nombre: ");
	fgets(p15, 50, stdin);
	//scanf("%s", &p1);
	printf("Valido \n");
	system("pause");
	system("cls"); printf("Introduce un nombre: ");
	fgets(p16, 50, stdin);
	//scanf("%s", &p1);
	printf("Valido \n");
	system("pause");
	system("cls");
	printf("Introduce un nombre: ");
	fgets(p17, 50, stdin);
	//scanf("%s", &p1);
	printf("Valido \n");
	system("pause");
	system("cls");
	printf("Introduce un nombre: ");
	fgets(p18, 50, stdin);
	//scanf("%s", &p1);
	printf("Valido \n");
	system("pause");
	system("cls");
	printf("Introduce un nombre: ");
	fgets(p19, 50, stdin);
	//scanf("%s", &p1);
	printf("Valido \n");
	system("pause");
	system("cls");
	printf("Introduce un nombre: ");
	fgets(p20, 50, stdin);
	//scanf("%s", &p1);
	printf("Valido \n");
	system("pause");
	system("cls");
	system("cls");
	system("pause");
	printf("\n %s \n %s \n %s \n %s \n %s \n %s \n %s \n %s \n %s \n %s \n %s \n %s \n %s \n %s \n %s \n %s \n %s \n %s \n %s \n %s \n", p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17, p18, p19, p20);
	system("pause");
	system("cls");
	system("pause");
	system("pause");
	system("pause");
	system("pause");
	system("pause");
	printf("\n %s \n %s \n %s \n %s \n %s \n %s \n %s \n %s \n %s \n %s \n %s \n %s \n %s \n %s \n %s \n %s \n %s \n %s \n %s \n %s \n", p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17, p18, p19, p20);
	system("pause");
	return 0;
}